---
title: "Armed_Conflict_Clean"
output: html_document
date: "2024-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.



```{r}
library(here)
library(tidyverse)
library(dplyr)
library(usethis)
library(countrycode)
here()


```

```{r}
data1 <- read.csv("Original_Data/maternalmortality.csv", header = TRUE)


data2 <- select(data1, Country.Name, X2000:X2019)

data3 <- pivot_longer(data2, cols=c(X2000:X2019),
                    names_to='year',
                    names_prefix = 'X',
                    values_to='MatMor') 

data3$year <- as.numeric(data3$year)

data4 <- read.csv("Original_Data/infantmortality.csv", header =  TRUE)


```

```{r}

week3 <- function(input_file, output_file){
  f_0 <- read.csv(input_file, header = TRUE)
  f_1 <- select(f_0, Country.Name, X2000:X2019)
  f_2 <- pivot_longer(f_1, cols=c(X2000:X2019),
                    names_to='year',
                    names_prefix = 'X',
                    values_to= 'Mortality')
  f_2$year <- as.numeric(f_2$year)
  write.csv(f_2, file = output_file, row.names = FALSE)

}

```

```{r} 
week33 <- function(input_file1){
  f_00 <- read.csv(input_file1, header = TRUE)
  f_11 <- select(f_00, Country.Name, X2000:X2019)
  f_22 <- pivot_longer(f_11, cols=c(X2000:X2019),
                    names_to='year',
                    names_prefix = 'X',
                    values_to= 'Mortality')
  f_22$year <- as.numeric(f_22$year)
  return(f_22)
}
```


```{r}
under5_function <- week33("Original_Data/under5mortality.csv")
infant_function <- week33("Original_Data/infantmortality.csv")
neonatal_function <- week33("Original_Data/neonatalmortality.csv")
maternal_function <- week33("Original_Data/maternalmortality.csv")
```


```{r}
list_mor <- list(under5_function,infant_function,neonatal_function,maternal_function)
allmor <- reduce(list_mor, full_join, by = c("Country.Name","year"))

```

```{r}
allmor$ISO <- countrycode(allmor$Country.Name, origin = "country.name", 
                           destination = "iso3c")
allmor1 <- select(allmor, -Country.Name)
write.csv(allmor1, file = "Clean_Data/allmor.csv", row.names = FALSE)
```

```{r}
disaster7 <- read.csv("Clean_Data/disaster_clean.csv")
c_data1<- read.csv("Original_Data/conflictdata.csv")

```

```{r}
disaster9 <- dplyr::rename(disaster7, year = Year)
```


```{r}
c_data2 <- group_by(c_data1, ISO, year)
c_data3 <- summarize(c_data2, death = sum(best))
c_data4 <- mutate(c_data3, is.conflict = ifelse(death < 25, 0, 1))
c_data5 <- mutate(c_data4, year = year + 1)
```

```{r}
cov_data1 <- read.csv("Original_Data/covariates.csv")



all1 <- list(allmor1,disaster9, cov_data1, c_data2)

all2 <- reduce(all1, full_join, by = c("year", "ISO"))

all3 <- list(c_data5, allmor1, disaster9)

all4 <- reduce(all3, full_join, by = c('ISO', 'year')) 

all5 <- left_join(cov_data1, all4, by = c('ISO', 'year') )

final_data <-  mutate(all5,
                is.conflict = replace_na(is.conflict, 0), 
                drought = replace_na(drought, 0),
                earthquake = replace_na(earthquake, 0), 
                death = replace_na(death, 0))

write.csv(final_data, file = "Clean_Data/armed_conflict.csv", row.names = FALSE)
```