---
title: "Visualization"
format: pdf
---

## Armed Conflict Data Visualization

```{r}
#| output: false
library(flextable)
library(xtable)
library(table1)
library(texreg)
library(gtsummary)
library(modelsummary)
library(tidyverse)
```

```{r}

```

```{r}
v2 <- read.csv("Clean_Data/armed_conflict_final.csv", header =TRUE)

label(v2$Under_5_Mortality) <- "Under 5"        # Under 5 mortality rate
label(v2$Infant_Mortality) <- "Infant"         # Infant mortality rate
label(v2$Neonatal_Mortality) <- "Neonatal"     # Neonatal mortality rate
label(v2$Maternal_Mortality) <- "Maternal"     # Maternal mortality rate

v2$is.conflict <- factor(v2$is.conflict, levels = c(0, 1), labels = c("NO", "YES"))
v2$drought <- factor(v2$drought, levels = c(0, 1), labels = c("No", "Yes"))
v2$earthquake <- factor(v2$earthquake, levels = c(0, 1), labels = c("No", "Yes"))


table1(~ drought+ earthquake+  Under_5_Mortality+ Infant_Mortality + Neonatal_Mortality
       + Maternal_Mortality| is.conflict, 
       data = v2, caption = "Table of baseline characteristics", 
       render.continuous = c(.="Median [Min, Max]"),
       overall=c(left="Total"), 
       topclass="Rtable1-grid Rtable1-center")


```

```{r}

finaldata <- read.csv("Clean_Data/armed_conflict_final.csv", header =TRUE)
finaldata1 <-  dplyr::select(finaldata, country_name, ISO, year, Maternal_Mortality, is.conflict)
finaldata1 <-  dplyr::filter(finaldata1, year < 2018)
finaldata1 <-  arrange(finaldata1, ISO, year)
finaldata1 <-  group_by(finaldata1, ISO)
finaldata1 <-   mutate(finaldata1, diffmatmor = Maternal_Mortality - Maternal_Mortality[1L]) 
finaldata2 <- filter(finaldata1, diffmatmor > 0)
```

```{r}
#| warning: false
plot1 <-ggplot(finaldata2, aes(x = year, y = Maternal_Mortality, group = ISO)) +
  geom_line(aes(color = as.factor(ISO)), alpha = 0.5) +
  xlim(c(2000,2017)) +
  scale_y_continuous(trans='log10') + 
  labs(y = "Maternal mortality", x = "Year", color = "Armed conflict") + 
  theme_bw()

plot1

```
