---
title: "w2"
output: html_document
date: "2024-09-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.



```{r}
library(here)
library(tidyverse)
library(dplyr)
library(usethis)
library(countrycode)
here()


```

```{r}
data1 <- read.csv("maternalmortality.csv", header = TRUE)


data2 <- select(data1, Country.Name, X2000:X2019)

data3 <- pivot_longer(data2, cols=c(X2000:X2019),
                    names_to='year',
                    names_prefix = 'X',
                    values_to='MatMor') 

data3$year <- as.numeric(data3$year)

write.csv(data3, file = "DATA/data3.csv", row.names = FALSE)
data4 <- read.csv("infantmortality.csv", header =  TRUE)


```

```{r}

week3 <- function(input_file, output_file){
  f_0 <- read.csv(input_file, header = TRUE)
  f_1 <- select(f_0, Country.Name, X2000:X2019)
  f_2 <- pivot_longer(f_1, cols=c(X2000:X2019),
                    names_to='year',
                    names_prefix = 'X',
                    values_to= 'Mortality')
  f_2$year <- as.numeric(f_2$year)
  write.csv(f_2, file = output_file, row.names = FALSE)

}

```

```{r} 
week33 <- function(input_file1){
  f_00 <- read.csv(input_file1, header = TRUE)
  f_11 <- select(f_00, Country.Name, X2000:X2019)
  f_22 <- pivot_longer(f_11, cols=c(X2000:X2019),
                    names_to='year',
                    names_prefix = 'X',
                    values_to= 'Mortality')
  f_22$year <- as.numeric(f_22$year)
  return(f_22)
}
```


```{r}
#test
under5_function <- week33("under5mortality.csv")
infant_function <- week33("infantmortality.csv")
neonatal_function <- week33("neonatalmortality.csv")
maternal_function <- week33("maternalmortality.csv")
```


```{r}
list_mor <- list(under5_function,infant_function,neonatal_function,maternal_function)
allmor <- reduce(list_mor, full_join, by = c("Country.Name","year"))

```

```{r}
allmor$ISO <- countrycode(allmor$Country.Name, origin = "country.name", 
                           destination = "iso3c")
allmor1 <- select(allmor, -Country.Name)
write.csv(allmor1, file = "allmor.csv", row.names = FALSE)
```

```{r}
disaster7 <- read.csv("disaster_clean.csv")
c_data1<- read.csv("conflictdata.csv")

```

```{r}
disaster9 <- dplyr::rename(disaster7, year = Year)
```


```{r}
c_data2 <- c_data1
c_data2$year <- c_data2$year + 1
c_data2$conflict_Yes <- !is.na(c_data2$conflict_id)
c_data2$conflict_Yes <- 1*c_data2$conflict_Yes

```

```{r}
cov_data1 <- read.csv("covariates.csv")



all1 <- list(allmor1,disaster9, cov_data1, c_data2)

all2 <- reduce(all1, full_join, by = c("year", "ISO"))


```




